### ISSUE TITLE
error in facial_exchange.py

### ISSUE THREAD

**Issue by mzprose** [pacifinapacific/StyleGAN_LatentEditor#10]
Hello,when I run this .py file,error happend,can you tell me how to solve?thank you!

"RuntimeError: No default TensorFlow session found. Please call dnnlib.tflib.init_tf()."

the complete code in dnnlib/tflib/tfutil.py:
def assert_tf_initialized():
    """Check that TensorFlow session has been initialized."""
    if tf.get_default_session() is None:
        raise RuntimeError("No default TensorFlow session found. Please call dnnlib.tflib.init_tf().")

**Comment by pacifinapacific** [comment]
I don't know your detailed environment, so I can't answer. did you run it according to the jupyter-notebook file? did you successfully convert the weights in the previous step of facial_exchange.py?

**Comment by mzprose** [comment]
I do run according to the jupyter-notebook file and have converted the weights, so there should be a problem with my operating environment? But other tasks, such as image_crossover.py, image_morphing.py, etc., all run successfully.

**Comment by pacifinapacific** [comment]
umm...It looks like facial_exchange.py is running in pytorch and not calling dnnlib. Can you show me the error log so that I can see at what stage the error is occurring?

**Comment by mzprose** [comment]
Traceback (most recent call last):
  File "facial_exchange.py", line 167, in <module>
    main()
  File "facial_exchange.py", line 37, in main
    g_all.load_state_dict(torch.load(args.weight_file, map_location=device))
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
  File "E:\Style Transfer\GAN_2020_12\StyleGAN_LatentEditor-master\dnnlib\tflib\network.py", line 271, in __setstate__
    tfutil.assert_tf_initialized()
  File "E:\Style Transfer\GAN_2020_12\StyleGAN_LatentEditor-master\dnnlib\tflib\tfutil.py", line 125, in assert_tf_initialized
    raise RuntimeError("No default TensorFlow session found. Please call dnnlib.tflib.init_tf().")
RuntimeError: No default TensorFlow session found. Please call dnnlib.tflib.init_tf().

**Comment by pacifinapacific** [comment]
I'm sorry, I don't know why you get the error in facial_exchange.py but not in image_crossover.py. 
The two codes should be the same until line 37.
Did you try it on google colaboratory?

**Comment by mzprose** [comment]
Ok, I will try again, thanks for your answer

**Comment by zmxhhh** [comment]
Hello, can you share the weight file?  The link provided by the author cannot be downloaded at this time.
